---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.14
  commands:
  - go build -v -a -o release/linux/amd64/drone-rcon
  environment:
    CGO_ENABLED: 0

- name: publish
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.linux.amd64
    daemon_off: false
    repo: shinobi9/drone-rcon-go
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: golang:1.14
  commands:
  - go build -v -a -o release/linux/arm64/drone-rcon
  environment:
    CGO_ENABLED: 0

- name: publish
  image: plugins/docker:linux-arm64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: docker/Dockerfile.linux.arm64
    daemon_off: false
    repo: shinobi9/drone-rcon-go
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag

---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: golang:1.14
  commands:
  - go build -v -a -o release/linux/arm/drone-rcon
  environment:
    CGO_ENABLED: 0

- name: publish
  image: plugins/docker:linux-arm
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: docker/Dockerfile.linux.arm
    daemon_off: false
    repo: shinobi9/drone-rcon-go
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag

---
kind: pipeline
name: tail

steps:
- name: manifest
  image: plugins/manifest
  settings:
    ignore_missing: true
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  event:
  - tag

depends_on:
- linux-amd64
- linux-arm64
- linux-arm