FROM plugins/base:linux-arm64

LABEL maintainer="shinobi9 <shinobi9c@outlook.com>" \
  org.label-schema.name="Drone RCON Support" \
  org.label-schema.vendor="shinobi9" \
  org.label-schema.schema-version="1.0"

COPY release/linux/arm64/drone-rcon /bin/

ENTRYPOINT ["/bin/drone-rcon"]